### ISSUE TITLE
I can't find the audio data for the EGTEA Gaze+ dataset

### ISSUE THREAD

**Issue by Full-Adder** [zeyun-zhong/AFFT#3]
I admire you all doing such wonderful work. I'm interested in the two datasets you used, but the .mp4 files I downloaded from the connection[https://cbs.ic.gatech.edu/fpv/#egtea_gaze_plus] don't contain audio. Is this because the datasets EGTEA Gaze+ don't contain audio? Where can I get the audio data from?

**Comment by zeyun-zhong** [comment]
Hi, 

thanks for your interest in our work. Please note that we do not use audio features for the EGTEA Gaze+ dataset.

According to Section 3.3 of the [paper](https://arxiv.org/pdf/2006.00626.pdf), the audio should be available. However, I have not found audio either. It may be worthwhile to contact the authors for further details.

Best regards,
Zeyun
